name: classic
summary: A classic shell environment for Ubuntu Core all-snap installations
description: This snap provides a full classic shell environment including dpkg and apt support.
version: 16.04
confinement: devmode
architectures: [ all ]
grade: devel
assumes: [snapd2.23]

apps:
  create:
    command: bin/create
    plugs: [classic-support]
  reset:
    command: bin/reset
    plugs: [classic-support]
  classic:
    command: bin/classic
    plugs: [classic-support]

parts:
  check:
    plugin: nil
    override-build: |
      shellcheck ./bin/*
    build-packages:
      - shellcheck
  copy:
    plugin: dump
    source: .
    after: [check]
